/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Duc Tai
 */
public class ManHinhChinh_KhachHang extends javax.swing.JFrame {

    /**
     * Creates new form ManHinhChinh_KhachHang
     */
    ImageIcon imgDatLich;
    ImageIcon imgDatLich_trang;
    ImageIcon imgFeedback;
    ImageIcon imgFeedback_trang;
    ImageIcon imgThanhToan;
    ImageIcon imgThanhToan_trang;
    public ManHinhChinh_KhachHang() {
        initComponents();
        this.setLocationRelativeTo(null);
        imgDatLich = new ImageIcon("src/Resources/datlich_manhinhmau.png");
        imgDatLich_trang = new ImageIcon("src/Resources/datlich_manhinh.png");
        imgFeedback = new ImageIcon("src/Resources/feedback_manhinhmau.png");
        imgFeedback_trang = new ImageIcon("src/Resources/feedback_manhinh.png");
        imgThanhToan =new ImageIcon("src/Resources/thanhToan_manhinhmau.png");
        imgThanhToan_trang = new ImageIcon("src/Resources/thanhToan_manhinh.png");
        setTitle("Giao diện khách hàng");
        
    }
String userName="";
    void setUsername(String username){
        userName =username;
        jLabelUsername.setText("Xin chào "+username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void resetBackground(JLabel jlb, JPanel jp, ImageIcon img){
        jlb.setIcon(img);
        jp.setBackground(new Color(255,255,255));
       
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTitle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelMenu = new javax.swing.JPanel();
        jPanelDatLich = new javax.swing.JPanel();
        jLabelDatLich = new javax.swing.JLabel();
        jPanelFeedback = new javax.swing.JPanel();
        jLabelFeedback = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();
        jLabelLogOut = new javax.swing.JLabel();
        jPanelThanhToan = new javax.swing.JPanel();
        jLabelThanhToan = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelTitle.setBackground(new java.awt.Color(218, 221, 247));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/welcome_khachhang.png"))); // NOI18N
        jLabel1.setText("Welcome Back,");

        javax.swing.GroupLayout jPanelTitleLayout = new javax.swing.GroupLayout(jPanelTitle);
        jPanelTitle.setLayout(jPanelTitleLayout);
        jPanelTitleLayout.setHorizontalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitleLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTitleLayout.setVerticalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanelMenu.setBackground(new java.awt.Color(255, 255, 255));

        jPanelDatLich.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDatLich.setPreferredSize(new java.awt.Dimension(90, 70));
        jPanelDatLich.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelDatLichMouseClicked(evt);
            }
        });

        jLabelDatLich.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/datlich_manhinh.png"))); // NOI18N

        javax.swing.GroupLayout jPanelDatLichLayout = new javax.swing.GroupLayout(jPanelDatLich);
        jPanelDatLich.setLayout(jPanelDatLichLayout);
        jPanelDatLichLayout.setHorizontalGroup(
            jPanelDatLichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 79, Short.MAX_VALUE)
            .addGroup(jPanelDatLichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelDatLichLayout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(jLabelDatLich)
                    .addContainerGap(16, Short.MAX_VALUE)))
        );
        jPanelDatLichLayout.setVerticalGroup(
            jPanelDatLichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(jPanelDatLichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelDatLichLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelDatLich)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanelFeedback.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFeedback.setPreferredSize(new java.awt.Dimension(90, 70));
        jPanelFeedback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelFeedbackMouseClicked(evt);
            }
        });

        jLabelFeedback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/feedback_manhinh.png"))); // NOI18N

        javax.swing.GroupLayout jPanelFeedbackLayout = new javax.swing.GroupLayout(jPanelFeedback);
        jPanelFeedback.setLayout(jPanelFeedbackLayout);
        jPanelFeedbackLayout.setHorizontalGroup(
            jPanelFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 79, Short.MAX_VALUE)
            .addGroup(jPanelFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelFeedbackLayout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(jLabelFeedback)
                    .addContainerGap(16, Short.MAX_VALUE)))
        );
        jPanelFeedbackLayout.setVerticalGroup(
            jPanelFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(jPanelFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelFeedbackLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelFeedback)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Thanh toán");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Feedback");

        jLabelUsername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/KhachHang.png"))); // NOI18N

        jLabelLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/logout.png"))); // NOI18N
        jLabelLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLogOutMouseClicked(evt);
            }
        });

        jPanelThanhToan.setBackground(new java.awt.Color(255, 255, 255));
        jPanelThanhToan.setPreferredSize(new java.awt.Dimension(90, 70));
        jPanelThanhToan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelThanhToanMouseClicked(evt);
            }
        });

        jLabelThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/thanhToan_manhinh.png"))); // NOI18N

        javax.swing.GroupLayout jPanelThanhToanLayout = new javax.swing.GroupLayout(jPanelThanhToan);
        jPanelThanhToan.setLayout(jPanelThanhToanLayout);
        jPanelThanhToanLayout.setHorizontalGroup(
            jPanelThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 79, Short.MAX_VALUE)
            .addGroup(jPanelThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelThanhToanLayout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(jLabelThanhToan)
                    .addContainerGap(16, Short.MAX_VALUE)))
        );
        jPanelThanhToanLayout.setVerticalGroup(
            jPanelThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(jPanelThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelThanhToanLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelThanhToan)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Đặt lịch thi đấu");

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel4)
                .addGap(70, 70, 70)
                .addComponent(jLabel2)
                .addGap(76, 76, 76)
                .addComponent(jLabel3))
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGap(489, 489, 489)
                .addComponent(jLabelLogOut))
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jPanelDatLich, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(jPanelThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelUsername)
                    .addComponent(jPanelFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabelUsername)
                .addGap(70, 70, 70)
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDatLich, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(76, 76, 76)
                .addComponent(jLabelLogOut))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
int iDatLich =1;
    private void jPanelDatLichMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDatLichMouseClicked
        // TODO add your handling code here:
        if(iDatLich==1){
            jPanelDatLich.setBackground(new Color(176,171,202));
            jLabelDatLich.setIcon(imgDatLich);
            iDatLich++;

            resetBackground(jLabelFeedback,jPanelFeedback, imgFeedback_trang);
            resetBackground(jLabelThanhToan,jPanelThanhToan,imgThanhToan_trang);
            
            iFeedback= iThanhToan =1;
        }
        else if (iDatLich==2){
            iDatLich=2;
            //this.toBack();
            DatLich manHinhDatLich = new DatLich();
            manHinhDatLich.setVisible(true);
            manHinhDatLich.toFront();
            manHinhDatLich.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }

    }//GEN-LAST:event_jPanelDatLichMouseClicked
int iFeedback =1;
    private void jPanelFeedbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelFeedbackMouseClicked
        // TODO add your handling code here:
        if(iFeedback==1){
            jPanelFeedback.setBackground(new Color(170,233,229));
            jLabelFeedback.setIcon(imgFeedback);
            iFeedback++;
            
            resetBackground(jLabelDatLich,jPanelDatLich, imgDatLich_trang);
            resetBackground(jLabelThanhToan,jPanelThanhToan,imgThanhToan_trang);

            
            iDatLich =iThanhToan=1;

        }
        else if (iFeedback==2){
            iFeedback=2;
            //this.toBack();
            ThemFeedback manHinhFeedback = new ThemFeedback();
            manHinhFeedback.setVisible(true);
            manHinhFeedback.toFront();
            manHinhFeedback.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }
    }//GEN-LAST:event_jPanelFeedbackMouseClicked

    private void jLabelLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogOutMouseClicked
        // TODO add your handling code here:
        int confirm =JOptionPane.showConfirmDialog(this, "Bạn muốn đăng xuất?", "Xác nhận",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE); 
        if(confirm == JOptionPane.YES_OPTION){
        
            DangNhap manHinhDangNhap = new DangNhap();
            manHinhDangNhap.show();
            dispose();
        }
    }//GEN-LAST:event_jLabelLogOutMouseClicked
int iThanhToan=1;
    private void jPanelThanhToanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelThanhToanMouseClicked
        // TODO add your handling code here:
        if(iThanhToan==1){
            jPanelThanhToan.setBackground(new Color(158,169,205));
            jLabelThanhToan.setIcon(imgThanhToan);
            iThanhToan++;
            
            resetBackground(jLabelDatLich,jPanelDatLich, imgDatLich_trang);
            resetBackground(jLabelFeedback,jPanelFeedback,imgFeedback_trang);

            
            iDatLich =iFeedback=1;

        }
        else if (iThanhToan==2){
            iThanhToan=2;
            //this.toBack();
            ThanhToan manHinhThanhToan = new ThanhToan();
            manHinhThanhToan.setThongTin(userName);
            manHinhThanhToan.setVisible(true);
            manHinhThanhToan.toFront();
            manHinhThanhToan.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }
    }//GEN-LAST:event_jPanelThanhToanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManHinhChinh_KhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManHinhChinh_KhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManHinhChinh_KhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManHinhChinh_KhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManHinhChinh_KhachHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelDatLich;
    private javax.swing.JLabel jLabelFeedback;
    private javax.swing.JLabel jLabelLogOut;
    private javax.swing.JLabel jLabelThanhToan;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPanel jPanelDatLich;
    private javax.swing.JPanel jPanelFeedback;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelThanhToan;
    private javax.swing.JPanel jPanelTitle;
    // End of variables declaration//GEN-END:variables
}
