/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Duc Tai
 */
public class ManHinhChinh_NhanVien extends javax.swing.JFrame {
    ImageIcon imgDungCu;
    ImageIcon imgDoUong;
    ImageIcon imgThemSan;
    ImageIcon imgThongKe;
    ImageIcon imgDungCu_trang;
    ImageIcon imgDoUong_trang;
    ImageIcon imgThemSan_trang;
    ImageIcon imgThongKe_trang;
    
    ImageIcon imgKhachHang;
    ImageIcon imgKhachHang_trang;
    ImageIcon imgQuanLiSan;
    ImageIcon imgQuanLiSan_trang;
    
    ImageIcon imgThemDoUong;
    ImageIcon imgThemDoUong_trang;
    ImageIcon imgThemDungCu;
    ImageIcon imgThemDungCu_trang;

    /**
     * Creates new form ManHinhChinh_KhachHang
     */
    public ManHinhChinh_NhanVien() {
        initComponents();
        this.setLocationRelativeTo(null);
        imgDungCu = new ImageIcon("src/Resources/sport-manhinhmaui.png");
        imgDoUong = new ImageIcon("src/Resources/drink_manhinhmau.png");
        imgThongKe = new ImageIcon("src/Resources/thongke_mau.png");
        imgThemSan = new ImageIcon("src/Resources/stadium_manhinhmau.png");
        
        imgDungCu_trang = new ImageIcon("src/Resources/sport_manhinh.png");
        imgDoUong_trang = new ImageIcon("src/Resources/drink_manhinh.png");
        imgThongKe_trang = new ImageIcon("src/Resources/thongke.png");
        imgThemSan_trang = new ImageIcon("src/Resources/stadium _manhinh.png");
        
        imgKhachHang = new ImageIcon("src/Resources/khachhang_manhinhmau.png");
        imgKhachHang_trang = new ImageIcon("src/Resources/khachhang_manhinh.png");
        imgQuanLiSan = new ImageIcon("src/Resources/san_manhinhmau.png");
        imgQuanLiSan_trang =new ImageIcon("src/Resources/san_manhinh.png");
        
        imgThemDoUong = new ImageIcon("src/Resources/themDoUong_manhinhmau.png");
        imgThemDoUong_trang = new ImageIcon("src/Resources/themDoUong_manhinh.png");
        imgThemDungCu = new ImageIcon("src/Resources/themDungCu_manhinhmau.png");
        imgThemDungCu_trang =new ImageIcon("src/Resources/themDungCu_manhinh.png");
        setTitle("Giao diện nhân viên");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTitle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelMenu = new javax.swing.JPanel();
        jPanelDoUong = new javax.swing.JPanel();
        jLabelDoUong = new javax.swing.JLabel();
        jPanelDungCu = new javax.swing.JPanel();
        jLabelDungCu = new javax.swing.JLabel();
        jPanelThemSan = new javax.swing.JPanel();
        jLabelThemSan = new javax.swing.JLabel();
        jPanelThongKe = new javax.swing.JPanel();
        jLabelThongKe = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanelQuanLiSan = new javax.swing.JPanel();
        jLabelQuanLiSan = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanelThemDoUong = new javax.swing.JPanel();
        jLabelThemDoUong = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanelThemDungCu = new javax.swing.JPanel();
        jLabelThemDungCu = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanelKhachHang = new javax.swing.JPanel();
        jLabelKhachHang = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();
        jLabelLogOut = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelTitle.setBackground(new java.awt.Color(134, 174, 209));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/welcome-back.png"))); // NOI18N
        jLabel1.setText("Welcome Back,");

        javax.swing.GroupLayout jPanelTitleLayout = new javax.swing.GroupLayout(jPanelTitle);
        jPanelTitle.setLayout(jPanelTitleLayout);
        jPanelTitleLayout.setHorizontalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitleLayout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTitleLayout.setVerticalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanelMenu.setBackground(new java.awt.Color(255, 255, 255));

        jPanelDoUong.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDoUong.setPreferredSize(new java.awt.Dimension(90, 70));
        jPanelDoUong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelDoUongMouseClicked(evt);
            }
        });

        jLabelDoUong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/drink_manhinh.png"))); // NOI18N

        javax.swing.GroupLayout jPanelDoUongLayout = new javax.swing.GroupLayout(jPanelDoUong);
        jPanelDoUong.setLayout(jPanelDoUongLayout);
        jPanelDoUongLayout.setHorizontalGroup(
            jPanelDoUongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDoUongLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabelDoUong)
                .addGap(15, 15, 15))
        );
        jPanelDoUongLayout.setVerticalGroup(
            jPanelDoUongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDoUongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDoUong)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelDungCu.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDungCu.setPreferredSize(new java.awt.Dimension(90, 70));
        jPanelDungCu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelDungCuMouseClicked(evt);
            }
        });

        jLabelDungCu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/sport_manhinh.png"))); // NOI18N

        javax.swing.GroupLayout jPanelDungCuLayout = new javax.swing.GroupLayout(jPanelDungCu);
        jPanelDungCu.setLayout(jPanelDungCuLayout);
        jPanelDungCuLayout.setHorizontalGroup(
            jPanelDungCuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDungCuLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabelDungCu)
                .addGap(14, 14, 14))
        );
        jPanelDungCuLayout.setVerticalGroup(
            jPanelDungCuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDungCuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDungCu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelThemSan.setBackground(new java.awt.Color(255, 255, 255));
        jPanelThemSan.setPreferredSize(new java.awt.Dimension(90, 70));
        jPanelThemSan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelThemSanMouseClicked(evt);
            }
        });

        jLabelThemSan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/stadium _manhinh.png"))); // NOI18N

        javax.swing.GroupLayout jPanelThemSanLayout = new javax.swing.GroupLayout(jPanelThemSan);
        jPanelThemSan.setLayout(jPanelThemSanLayout);
        jPanelThemSanLayout.setHorizontalGroup(
            jPanelThemSanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelThemSanLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabelThemSan)
                .addGap(15, 15, 15))
        );
        jPanelThemSanLayout.setVerticalGroup(
            jPanelThemSanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThemSanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelThemSan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelThongKe.setBackground(new java.awt.Color(255, 255, 255));
        jPanelThongKe.setPreferredSize(new java.awt.Dimension(90, 70));
        jPanelThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelThongKeMouseClicked(evt);
            }
        });

        jLabelThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/thongke.png"))); // NOI18N

        javax.swing.GroupLayout jPanelThongKeLayout = new javax.swing.GroupLayout(jPanelThongKe);
        jPanelThongKe.setLayout(jPanelThongKeLayout);
        jPanelThongKeLayout.setHorizontalGroup(
            jPanelThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelThongKeLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabelThongKe)
                .addGap(15, 15, 15))
        );
        jPanelThongKeLayout.setVerticalGroup(
            jPanelThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThongKeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelThongKe)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Quản lý đồ uống");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Quản lý dụng cụ");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Thống kê doanh thu");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Thêm sân");

        jPanelQuanLiSan.setBackground(new java.awt.Color(255, 255, 255));
        jPanelQuanLiSan.setPreferredSize(new java.awt.Dimension(90, 70));
        jPanelQuanLiSan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelQuanLiSanMouseClicked(evt);
            }
        });

        jLabelQuanLiSan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/san_manhinh.png"))); // NOI18N

        javax.swing.GroupLayout jPanelQuanLiSanLayout = new javax.swing.GroupLayout(jPanelQuanLiSan);
        jPanelQuanLiSan.setLayout(jPanelQuanLiSanLayout);
        jPanelQuanLiSanLayout.setHorizontalGroup(
            jPanelQuanLiSanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuanLiSanLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelQuanLiSan)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanelQuanLiSanLayout.setVerticalGroup(
            jPanelQuanLiSanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuanLiSanLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabelQuanLiSan)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Quản lý sân");

        jPanelThemDoUong.setBackground(new java.awt.Color(255, 255, 255));
        jPanelThemDoUong.setPreferredSize(new java.awt.Dimension(90, 70));
        jPanelThemDoUong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelThemDoUongMouseClicked(evt);
            }
        });

        jLabelThemDoUong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/themDoUong_manhinh.png"))); // NOI18N

        javax.swing.GroupLayout jPanelThemDoUongLayout = new javax.swing.GroupLayout(jPanelThemDoUong);
        jPanelThemDoUong.setLayout(jPanelThemDoUongLayout);
        jPanelThemDoUongLayout.setHorizontalGroup(
            jPanelThemDoUongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThemDoUongLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelThemDoUong)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanelThemDoUongLayout.setVerticalGroup(
            jPanelThemDoUongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThemDoUongLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabelThemDoUong)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Thêm đồ uống");

        jPanelThemDungCu.setBackground(new java.awt.Color(255, 255, 255));
        jPanelThemDungCu.setPreferredSize(new java.awt.Dimension(90, 70));
        jPanelThemDungCu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelThemDungCuMouseClicked(evt);
            }
        });

        jLabelThemDungCu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/themDungCu_manhinh.png"))); // NOI18N

        javax.swing.GroupLayout jPanelThemDungCuLayout = new javax.swing.GroupLayout(jPanelThemDungCu);
        jPanelThemDungCu.setLayout(jPanelThemDungCuLayout);
        jPanelThemDungCuLayout.setHorizontalGroup(
            jPanelThemDungCuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelThemDungCuLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabelThemDungCu)
                .addGap(14, 14, 14))
        );
        jPanelThemDungCuLayout.setVerticalGroup(
            jPanelThemDungCuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThemDungCuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelThemDungCu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Thêm dụng cụ");

        jPanelKhachHang.setBackground(new java.awt.Color(255, 255, 255));
        jPanelKhachHang.setPreferredSize(new java.awt.Dimension(90, 70));
        jPanelKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelKhachHangMouseClicked(evt);
            }
        });

        jLabelKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/khachhang_manhinh.png"))); // NOI18N

        javax.swing.GroupLayout jPanelKhachHangLayout = new javax.swing.GroupLayout(jPanelKhachHang);
        jPanelKhachHang.setLayout(jPanelKhachHangLayout);
        jPanelKhachHangLayout.setHorizontalGroup(
            jPanelKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKhachHangLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelKhachHang)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanelKhachHangLayout.setVerticalGroup(
            jPanelKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKhachHangLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabelKhachHang)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Quản lý khách hàng");

        jLabelUsername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/customer-support.png"))); // NOI18N

        jLabelLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/logout.png"))); // NOI18N
        jLabelLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLogOutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jPanelDoUong, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelThemDoUong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))))
                .addGap(74, 74, 74)
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDungCu, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(jPanelThemDungCu, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelQuanLiSan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelMenuLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanelThemSan, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel6)))))
                        .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelMenuLayout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jLabel9))
                            .addGroup(jPanelMenuLayout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(jPanelThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelMenuLayout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(jPanelKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)))
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuLayout.createSequentialGroup()
                        .addComponent(jLabelUsername)
                        .addGap(81, 81, 81))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuLayout.createSequentialGroup()
                        .addComponent(jLabelLogOut)
                        .addContainerGap())))
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelUsername)
                .addGap(29, 29, 29)
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelDungCu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelDoUong, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(48, 48, 48)
                        .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanelThemDungCu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelThemDoUong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)))
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelQuanLiSan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addGap(47, 47, 47)
                        .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanelThemSan, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))))
                .addGap(8, 8, 8)
                .addComponent(jLabelLogOut)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void resetBackground(JLabel jlb, JPanel jp, ImageIcon img){
        jlb.setIcon(img);
        jp.setBackground(new Color(255,255,255));
       
    }
    void setUsername(String username){
        jLabelUsername.setText("Xin chào "+username);
    }
    int iDungCu =1;
    private void jPanelDungCuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDungCuMouseClicked
        // TODO add your handling code here:
        if(iDungCu==1){
            jPanelDungCu.setBackground(new Color(170,227,167));
            jLabelDungCu.setIcon(imgDungCu);
            iDungCu++;
            resetBackground(jLabelDoUong,jPanelDoUong, imgDoUong_trang);
            resetBackground(jLabelThongKe,jPanelThongKe, imgThongKe_trang);
            resetBackground(jLabelThemSan,jPanelThemSan, imgThemSan_trang);
            resetBackground(jLabelQuanLiSan,jPanelQuanLiSan, imgQuanLiSan_trang);
            resetBackground(jLabelThemDungCu,jPanelThemDungCu, imgThemDungCu_trang);
            resetBackground(jLabelKhachHang,jPanelKhachHang, imgKhachHang_trang);
            resetBackground(jLabelThemDoUong,jPanelThemDoUong, imgThemDoUong_trang);
            
            iDoUong = iThemDoUong= iQuanLiSan= iThemSan =iThemDungCu= iKhachHang =iThongKe =1;
            
            
        }
        else if (iDungCu==2){
            iDungCu=2;
            //this.toBack();
            QuanLyDungCu manHinhQuanLiDungCu = new QuanLyDungCu();
            manHinhQuanLiDungCu.setVisible(true);
            manHinhQuanLiDungCu.toFront();
            manHinhQuanLiDungCu.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }
    }//GEN-LAST:event_jPanelDungCuMouseClicked
int iDoUong =1;
    private void jPanelDoUongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDoUongMouseClicked
        // TODO add your handling code here:
        if(iDoUong==1){
            jPanelDoUong.setBackground(new Color(170,233,229));
            jLabelDoUong.setIcon(imgDoUong);
            iDoUong++;
            
            resetBackground(jLabelDungCu,jPanelDungCu, imgDungCu_trang);
            resetBackground(jLabelThongKe,jPanelThongKe, imgThongKe_trang);
            resetBackground(jLabelThemSan,jPanelThemSan, imgThemSan_trang);
            resetBackground(jLabelQuanLiSan,jPanelQuanLiSan, imgQuanLiSan_trang);
            resetBackground(jLabelThemDungCu,jPanelThemDungCu, imgThemDungCu_trang);
            resetBackground(jLabelKhachHang,jPanelKhachHang, imgKhachHang_trang);
            resetBackground(jLabelThemDoUong,jPanelThemDoUong, imgThemDoUong_trang);
            
            iDungCu = iThemDoUong= iQuanLiSan= iThemSan =iThemDungCu= iKhachHang =iThongKe =1;
        }
        else if (iDoUong==2){
            iDoUong=2;
            //this.toBack();
            QuanLyDoUong manHinhQuanLiDoUong = new QuanLyDoUong();
            manHinhQuanLiDoUong.setVisible(true);
            manHinhQuanLiDoUong.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            manHinhQuanLiDoUong.toFront();
        }
                
    }//GEN-LAST:event_jPanelDoUongMouseClicked
int iThongKe=1;
    private void jPanelThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelThongKeMouseClicked
        // TODO add your handling code here:
        if(iThongKe==1){
            jPanelThongKe.setBackground(new Color(240,222,253));
            jLabelThongKe.setIcon(imgThongKe);
            iThongKe++;
            
            resetBackground(jLabelDoUong,jPanelDoUong, imgDoUong_trang);
            resetBackground(jLabelDungCu,jPanelDungCu, imgDungCu_trang);
            resetBackground(jLabelThemSan,jPanelThemSan, imgThemSan_trang);
            resetBackground(jLabelQuanLiSan,jPanelQuanLiSan, imgQuanLiSan_trang);
            resetBackground(jLabelThemDungCu,jPanelThemDungCu, imgThemDungCu_trang);
            resetBackground(jLabelKhachHang,jPanelKhachHang, imgKhachHang_trang);
            resetBackground(jLabelThemDoUong,jPanelThemDoUong, imgThemDoUong_trang);
            
            iDoUong = iThemDoUong= iQuanLiSan= iThemSan =iThemDungCu= iKhachHang =iDungCu =1;
            
        }
        else if (iThongKe==2){
            iThongKe=2;
            //this.toBack();
            ThongKe manHinhThongKe = new ThongKe();
            manHinhThongKe.setVisible(true);
            manHinhThongKe.toFront();
            manHinhThongKe.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }
    }//GEN-LAST:event_jPanelThongKeMouseClicked
int iThemSan=1;
    private void jPanelThemSanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelThemSanMouseClicked
        // TODO add your handling code here:
        if(iThemSan==1){
            jPanelThemSan.setBackground(new Color(163,214,212));
            jLabelThemSan.setIcon(imgThemSan);
            iThemSan++;
            
            resetBackground(jLabelDoUong,jPanelDoUong, imgDoUong_trang);
            resetBackground(jLabelDungCu,jPanelDungCu, imgDungCu_trang);
            resetBackground(jLabelThongKe,jPanelThongKe, imgThongKe_trang);
            resetBackground(jLabelQuanLiSan,jPanelQuanLiSan, imgQuanLiSan_trang);
            resetBackground(jLabelThemDungCu,jPanelThemDungCu, imgThemDungCu_trang);
            resetBackground(jLabelKhachHang,jPanelKhachHang, imgKhachHang_trang);
            resetBackground(jLabelThemDoUong,jPanelThemDoUong, imgThemDoUong_trang);
            
            iDoUong = iThemDoUong= iQuanLiSan= iThongKe =iThemDungCu= iKhachHang =iDungCu =1;
            
        }
        else if (iThemSan==2){
            iThemSan=2;
            //this.toBack();
            ThemSan manHinhThemSan = new ThemSan();
            manHinhThemSan.setVisible(true);
            manHinhThemSan.toFront();
            manHinhThemSan.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }
    }//GEN-LAST:event_jPanelThemSanMouseClicked
int iThemDungCu =1;
    private void jPanelThemDungCuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelThemDungCuMouseClicked
        // TODO add your handling code here:
        if(iThemDungCu==1){
            jPanelThemDungCu.setBackground(new Color(170,227,167));
            jLabelThemDungCu.setIcon(imgThemDungCu);
            iThemDungCu++;
            
            resetBackground(jLabelDoUong,jPanelDoUong, imgDoUong_trang);
            resetBackground(jLabelQuanLiSan,jPanelQuanLiSan, imgQuanLiSan_trang);
            resetBackground(jLabelKhachHang,jPanelKhachHang, imgKhachHang_trang);
            resetBackground(jLabelDungCu,jPanelDungCu, imgDungCu_trang);
            resetBackground(jLabelThemDoUong,jPanelThemDoUong, imgThemDoUong_trang);
            resetBackground(jLabelThemSan,jPanelThemSan, imgThemSan_trang);
            resetBackground(jLabelThongKe,jPanelThongKe, imgThongKe_trang);
            iDoUong = iQuanLiSan = iKhachHang = iDungCu = iThemDoUong = iThemSan 
                    = iThongKe =1;
        }
        else if (iThemDungCu==2){
            iThemDungCu=2;
            //this.toBack();
            ThemDungCu manHinhThemDungCu = new ThemDungCu();
            manHinhThemDungCu.setVisible(true);
            manHinhThemDungCu.toFront();
            manHinhThemDungCu.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            
        }
    }//GEN-LAST:event_jPanelThemDungCuMouseClicked
int iThemDoUong =1;
    private void jPanelThemDoUongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelThemDoUongMouseClicked
        // TODO add your handling code here:
        if(iThemDoUong==1){
            jPanelThemDoUong.setBackground(new Color(170,233,229));
            jLabelThemDoUong.setIcon(imgThemDoUong);
            iThemDoUong++;
            
            resetBackground(jLabelDoUong,jPanelDoUong, imgDoUong_trang);
            resetBackground(jLabelQuanLiSan,jPanelQuanLiSan, imgQuanLiSan_trang);
            resetBackground(jLabelKhachHang,jPanelKhachHang, imgKhachHang_trang);
            resetBackground(jLabelDungCu,jPanelDungCu, imgDungCu_trang);
            resetBackground(jLabelThemDungCu,jPanelThemDungCu, imgThemDungCu_trang);
            resetBackground(jLabelThemSan,jPanelThemSan, imgThemSan_trang);
            resetBackground(jLabelThongKe,jPanelThongKe, imgThongKe_trang);
            iDoUong = iQuanLiSan = iKhachHang = iDungCu = iThemDungCu = iThemSan 
                    = iThongKe =1;
        }
        else if (iThemDoUong==2){
            iThemDoUong=2;
            //this.toBack();
            ThemDoUong manHinhThemDoUong = new ThemDoUong();
            manHinhThemDoUong.setVisible(true);
            manHinhThemDoUong.toFront();
            manHinhThemDoUong.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }
    }//GEN-LAST:event_jPanelThemDoUongMouseClicked
int iQuanLiSan =1;
    private void jPanelQuanLiSanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelQuanLiSanMouseClicked
        // TODO add your handling code here:
        if(iQuanLiSan==1){
            jPanelQuanLiSan.setBackground(new Color(163,214,212));
            jLabelQuanLiSan.setIcon(imgQuanLiSan);
            iQuanLiSan++;
            
            resetBackground(jLabelDoUong,jPanelDoUong, imgDoUong_trang);
            resetBackground(jLabelThemDoUong,jPanelThemDoUong, imgThemDoUong_trang);
            resetBackground(jLabelKhachHang,jPanelKhachHang, imgKhachHang_trang);
            resetBackground(jLabelDungCu,jPanelDungCu, imgDungCu_trang);
            resetBackground(jLabelThemDungCu,jPanelThemDungCu, imgThemDungCu_trang);
            resetBackground(jLabelThemSan,jPanelThemSan, imgThemSan_trang);
            resetBackground(jLabelThongKe,jPanelThongKe, imgThongKe_trang);
            
            iDoUong = iThemDoUong = iKhachHang = iDungCu = iThemDungCu = iThemSan 
                    = iThongKe =1;
        }
        else if (iQuanLiSan==2){
            iQuanLiSan=2;
            //this.toBack();
            QuanLySan manHinhQuanLySan = new QuanLySan();
            manHinhQuanLySan.setVisible(true);
            manHinhQuanLySan.toFront();
            manHinhQuanLySan.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }
    }//GEN-LAST:event_jPanelQuanLiSanMouseClicked
int iKhachHang =1;
    private void jPanelKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelKhachHangMouseClicked
        // TODO add your handling code here:
        if(iKhachHang==1){
            jPanelKhachHang.setBackground(new Color(199,228,167));
            jLabelKhachHang.setIcon(imgKhachHang);
            iKhachHang++;
            
            resetBackground(jLabelDoUong,jPanelDoUong, imgDoUong_trang);
            resetBackground(jLabelThemDoUong,jPanelThemDoUong, imgThemDoUong_trang);
            resetBackground(jLabelQuanLiSan,jPanelQuanLiSan, imgQuanLiSan_trang);
            resetBackground(jLabelDungCu,jPanelDungCu, imgDungCu_trang);
            resetBackground(jLabelThemDungCu,jPanelThemDungCu, imgThemDungCu_trang);
            resetBackground(jLabelThemSan,jPanelThemSan, imgThemSan_trang);
            resetBackground(jLabelThongKe,jPanelThongKe, imgThongKe_trang);
            
            iDoUong = iThemDoUong = iQuanLiSan = iDungCu = iThemDungCu = iThemSan 
                    = iThongKe =1;
        }
        else if (iKhachHang==2){
            iKhachHang=2;
            //this.toBack();
            QuanLyKhachHang manHinhQuanLyKhachHang = new QuanLyKhachHang();
            manHinhQuanLyKhachHang.setVisible(true);
            manHinhQuanLyKhachHang.toFront();
            manHinhQuanLyKhachHang.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }
    }//GEN-LAST:event_jPanelKhachHangMouseClicked

    private void jLabelLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogOutMouseClicked
        // TODO add your handling code here:
        int confirm =JOptionPane.showConfirmDialog(this, "Bạn muốn đăng xuất?", "Xác nhận",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE); 
        if(confirm == JOptionPane.YES_OPTION){
            DangNhap manHinhDangNhap = new DangNhap();
            manHinhDangNhap.show();
            dispose();
        }
    }//GEN-LAST:event_jLabelLogOutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManHinhChinh_NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManHinhChinh_NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManHinhChinh_NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManHinhChinh_NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManHinhChinh_NhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDoUong;
    private javax.swing.JLabel jLabelDungCu;
    private javax.swing.JLabel jLabelKhachHang;
    private javax.swing.JLabel jLabelLogOut;
    private javax.swing.JLabel jLabelQuanLiSan;
    private javax.swing.JLabel jLabelThemDoUong;
    private javax.swing.JLabel jLabelThemDungCu;
    private javax.swing.JLabel jLabelThemSan;
    private javax.swing.JLabel jLabelThongKe;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPanel jPanelDoUong;
    private javax.swing.JPanel jPanelDungCu;
    private javax.swing.JPanel jPanelKhachHang;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelQuanLiSan;
    private javax.swing.JPanel jPanelThemDoUong;
    private javax.swing.JPanel jPanelThemDungCu;
    private javax.swing.JPanel jPanelThemSan;
    private javax.swing.JPanel jPanelThongKe;
    private javax.swing.JPanel jPanelTitle;
    // End of variables declaration//GEN-END:variables
}
