/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import ConnectDB.OracleConnect;
import Process.SanTheThao;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kim Lien
 */
public class QuanLySan extends javax.swing.JFrame {

    /**
     * Creates new form QuanLySan
     */
    public QuanLySan() {
        initComponents();
        setVisible(true);
        TaoTableField();
//         URL urlIconSport = ThemSan.class.getResource("icon_qlysan.png");
//        Image img = Toolkit.getDefaultToolkit().createImage(urlIconSport);
//        this.setIconImage(img);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMaSan = new javax.swing.JTextField();
        txtTenSan = new javax.swing.JTextField();
        txtKichThuoc = new javax.swing.JTextField();
        txtMucGia = new javax.swing.JTextField();
        txtTinhTrang = new javax.swing.JTextField();
        txtGhiChu = new javax.swing.JTextField();
        btXoa = new javax.swing.JButton();
        btSua = new javax.swing.JButton();
        btThoat = new javax.swing.JButton();
        btTimKiem = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbField = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ THÔNG TIN SÂN");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Mã sân");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 119, -1, 24));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Tên sân");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 172, -1, 19));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Kích thước");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 212, 86, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Mức giá");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 257, 78, 19));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Tình trạng");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 301, -1, 28));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Ghi chú");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 351, 75, 24));
        getContentPane().add(txtMaSan, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 119, 248, 27));

        txtTenSan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenSanActionPerformed(evt);
            }
        });
        getContentPane().add(txtTenSan, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 164, 248, 27));
        getContentPane().add(txtKichThuoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 209, 249, 27));
        getContentPane().add(txtMucGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 254, 249, 29));
        getContentPane().add(txtTinhTrang, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 303, 250, 29));
        getContentPane().add(txtGhiChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 350, 250, 32));

        btXoa.setBackground(new java.awt.Color(153, 204, 255));
        btXoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Messaging-Trash-icon.png"))); // NOI18N
        btXoa.setText("Xóa");
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 600, 100, -1));

        btSua.setBackground(new java.awt.Color(153, 204, 255));
        btSua.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icon_update.png"))); // NOI18N
        btSua.setText("Sửa");
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });
        getContentPane().add(btSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 600, 100, -1));

        btThoat.setBackground(new java.awt.Color(153, 204, 255));
        btThoat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icon_exit.png"))); // NOI18N
        btThoat.setText("Thoát");
        btThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThoatActionPerformed(evt);
            }
        });
        getContentPane().add(btThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 600, -1, -1));

        btTimKiem.setBackground(new java.awt.Color(153, 204, 255));
        btTimKiem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Very-Basic-Search-icon.png"))); // NOI18N
        btTimKiem.setText("Tìm kiếm");
        btTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimKiemActionPerformed(evt);
            }
        });
        getContentPane().add(btTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 29, -1, 35));

        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });
        getContentPane().add(txtTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 31, 254, 33));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Nhập mã sân");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 29, 101, 33));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("THÔNG TIN CHI TIẾT CỦA SÂN");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 82, 481, 27));

        tbField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 1, true));
        tbField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbField.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã sân", "Tên sân", "Kích thước", "Mức giá", "Tình trạng", "Ghi chú"
            }
        ));
        tbField.setGridColor(new java.awt.Color(0, 153, 51));
        tbField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbFieldMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbField);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 770, 170));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/AdobeStock_212673770_Preview.jpeg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 810, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents
DefaultTableModel tblModelTT;
    public void TaoTableField(){
        tblModelTT = new DefaultTableModel();
        String tieuDe[]={"Mã sân","Tên sân","Kích thước","Mức giá","Tình trạng",
            "Ghi chú"};
        tblModelTT.setColumnIdentifiers(tieuDe);
        try(Connection con = OracleConnect.GetOracleConnect()){
            String row[] = new String [6];
            String strSQL = "Select * from FIELD";
            Statement stat = con.createStatement();
            ResultSet rs = stat.executeQuery(strSQL);
            while (rs.next()){
                row[0] = rs.getString(1);
                row[1] = rs.getString(2);
                row[2] = rs.getString(3);
                row[3] = rs.getString(4);
                row[4] = rs.getString(5);
                row[5] = rs.getString(6);
                tblModelTT.addRow(row);
            }
        }
        catch (Exception e) {
            System.out.print(e);
        }
     tbField.setModel(tblModelTT);
     setVisible(true);
}
    private void txtTenSanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenSanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenSanActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        // TODO add your handling code here:
        int indexTB = tbField.getSelectedRow();
        int ret = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa", "Xóa thông"
            + "tin sân", JOptionPane.YES_NO_OPTION);
        if (ret == JOptionPane.YES_OPTION) {
            SanTheThao san = new SanTheThao();
            int countRecord = san.XoaSan(txtMaSan.getText());
            if (countRecord > 0) {
                JOptionPane.showMessageDialog(this, "Xóa thông tin sân thành công");
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thông tin sân thất bại");
            }
            if (indexTB < tblModelTT.getRowCount() && indexTB >= 0) {
                tblModelTT.removeRow(indexTB);
            }
        }
    }//GEN-LAST:event_btXoaActionPerformed

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed
        // TODO add your handling code here:
        int ret = JOptionPane.showConfirmDialog(null,"Bạn có muốn sửa dữ liệu",
            "Sửa dữ liệu",JOptionPane.YES_NO_OPTION);
        if (ret == JOptionPane.YES_OPTION) {
            String masan = txtMaSan.getText();
            String tensan = txtTenSan.getText();
            String kichthuoc = txtKichThuoc.getText();
            String mucgia = txtMucGia.getText();
            String tinhtrang = txtTinhTrang.getText();
            String ghichu = txtGhiChu.getText();
            int indexTB = tbField.getSelectedRow();

            if (masan.equals(tblModelTT.getValueAt(indexTB, 0))) {
                SanTheThao san = new SanTheThao();
                //Lấy kết quả từ CSDL
                int countRecord = san.SuaSan(masan, tensan, kichthuoc, mucgia, tinhtrang, ghichu);
                if(countRecord>0){
                    JOptionPane.showMessageDialog(this, "Sửa thông tin sân thành công!");
                }
                else{
                    JOptionPane.showMessageDialog(this, "Sửa thông tin sân thất bại!");
                }
                if (indexTB < tblModelTT.getRowCount() && indexTB >= 0) {
                    tblModelTT.setValueAt(txtTenSan.getText(), indexTB, 1);
                    tblModelTT.setValueAt(txtKichThuoc.getText(), indexTB, 2);
                    tblModelTT.setValueAt(txtMucGia.getText(), indexTB, 3);
                    tblModelTT.setValueAt(txtTinhTrang.getText(), indexTB, 4);
                    tblModelTT.setValueAt(txtGhiChu.getText(), indexTB, 5);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Không được sửa mã sân");
            }
        }
    }//GEN-LAST:event_btSuaActionPerformed

    private void btThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThoatActionPerformed
        // TODO add your handling code here:
        int ret = JOptionPane.showConfirmDialog(null,"Bạn có muốn thoát",
            "Thoát",JOptionPane.YES_NO_OPTION);
        if(ret == JOptionPane.YES_OPTION)
        System.exit(0);
    }//GEN-LAST:event_btThoatActionPerformed

    private void btTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimKiemActionPerformed
        String gtri = this.txtTimKiem.getText();
        if (gtri.length() > 0) {
            String sql = "select * from FIELD where FIELDID like '%" + gtri + "%' " ;
            try ( Connection con = OracleConnect.GetOracleConnect()) {
                // Tạo đối tượng thực thi câu lệnh Select
                PreparedStatement prest = con.prepareStatement(sql);
                ResultSet rs = prest.executeQuery(sql);
                if (rs.next()) {
                    tblModelTT.getDataVector().removeAllElements();
                    while (rs.next()) {
                        String row[] = new String[6];
                        row[0] = rs.getString(1);
                        row[1] = rs.getString(2);
                        row[2] = rs.getString(3);
                        row[3] = rs.getString(4);
                        row[4] = rs.getString(5);
                        row[5] = rs.getString(6);
                        tblModelTT.addRow(row);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Không tìm thấy sân");
                }
            } catch (Exception e) {
                System.out.print(e);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Hãy nhập mã sân để tìm kiếm");
        }
    }//GEN-LAST:event_btTimKiemActionPerformed

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void tbFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbFieldMouseClicked
        // TODO add your handling code here:
        int indexTB = tbField.getSelectedRow();
        if (indexTB < tblModelTT.getRowCount() && indexTB >=0)
        txtMaSan.setText(tblModelTT.getValueAt(indexTB, 0).toString());
        txtTenSan.setText(tblModelTT.getValueAt(indexTB, 1).toString());
        txtKichThuoc.setText(tblModelTT.getValueAt(indexTB, 2).toString());
        txtMucGia.setText(tblModelTT.getValueAt(indexTB, 3).toString());
        txtTinhTrang.setText(tblModelTT.getValueAt(indexTB, 4).toString());
        txtGhiChu.setText(tblModelTT.getValueAt(indexTB, 5).toString());
    }//GEN-LAST:event_tbFieldMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLySan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLySan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLySan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLySan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLySan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSua;
    private javax.swing.JButton btThoat;
    private javax.swing.JButton btTimKiem;
    private javax.swing.JButton btXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbField;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtKichThuoc;
    private javax.swing.JTextField txtMaSan;
    private javax.swing.JTextField txtMucGia;
    private javax.swing.JTextField txtTenSan;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtTinhTrang;
    // End of variables declaration//GEN-END:variables
}
