/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import ConnectDB.OracleConnect;
import Process.DoUong;
import Process.KhachHang;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kim Lien
 */
public class QuanLyKhachHang extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyKhachHang
     */
    public QuanLyKhachHang() {
        initComponents();
        setVisible(true);
        TaoTableKhachHang();
//        URL urlIconSport = QuanLyKhachHang.class.getResource("group.png");
//        Image img = Toolkit.getDefaultToolkit().createImage(urlIconSport);
//        this.setIconImage(img);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDiaChi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtGhiChu = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbKhachHang = new javax.swing.JTable();
        txtMaKH = new javax.swing.JTextField();
        txtusername = new javax.swing.JTextField();
        btXoa = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        btSua = new javax.swing.JButton();
        txtTenKH = new javax.swing.JTextField();
        btThoat = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btTimKiem = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtSLDat = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtSdt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtLoaiKH = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ THÔNG TIN KHÁCH HÀNG");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 232, 254, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Địa chỉ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 228, 74, 24));
        getContentPane().add(txtGhiChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 312, 254, -1));

        tbKhachHang.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 1, true));
        tbKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã khách hàng", "Tên đăng nhập", "Tên khách hàng", "Số điện thoại", "Địa chỉ", "Số lần đặt", "Loại khách hàng", "Ghi chú"
            }
        ));
        tbKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbKhachHangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbKhachHang);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 810, 160));
        getContentPane().add(txtMaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 117, 254, -1));

        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 143, 254, -1));

        btXoa.setBackground(new java.awt.Color(153, 204, 255));
        btXoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icon_delete.png"))); // NOI18N
        btXoa.setText("Xóa");
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 520, 90, 38));

        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });
        getContentPane().add(txtTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 280, 30));

        btSua.setBackground(new java.awt.Color(153, 204, 255));
        btSua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icon_update.png"))); // NOI18N
        btSua.setText("Sửa");
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });
        getContentPane().add(btSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, 100, 35));
        getContentPane().add(txtTenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 173, 254, -1));

        btThoat.setBackground(new java.awt.Color(153, 204, 255));
        btThoat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icon_exit.png"))); // NOI18N
        btThoat.setText("Thoát");
        btThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThoatActionPerformed(evt);
            }
        });
        getContentPane().add(btThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 520, -1, 38));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/id-card.png"))); // NOI18N
        jLabel7.setText("Nhập mã khách hàng");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 180, 30));

        btTimKiem.setBackground(new java.awt.Color(153, 204, 255));
        btTimKiem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icon_search.png"))); // NOI18N
        btTimKiem.setText("Tìm kiếm");
        btTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimKiemActionPerformed(evt);
            }
        });
        getContentPane().add(btTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Số lần đặt");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 259, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Mã khách hàng");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 113, 94, 24));
        getContentPane().add(txtSLDat, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 258, 254, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Tên khách hàng");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 172, 159, 19));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Loại khách hàng");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 288, 159, -1));
        getContentPane().add(txtSdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 199, 254, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Tên đăng nhập");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 143, -1, 17));
        getContentPane().add(txtLoaiKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 287, 254, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("THÔNG TIN CHI TIẾT CỦA KHÁCH HÀNG");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 68, 481, 27));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Số điện thoại");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 198, 159, 19));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Ghi chú");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 313, 110, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/AdobeStock_436008703_Preview.jpeg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 830, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents
DefaultTableModel tblModelTT;
public void TaoTableKhachHang(){
        tblModelTT = new DefaultTableModel();
        String tieuDe[]={"Mã khách hàng","Tên đăng nhập","Tên khách hàng","Số điện thoại",
            "Địa chỉ","Số lần đặt","Loại khách hàng","Ghi chú"};
        tblModelTT.setColumnIdentifiers(tieuDe);

        try(Connection con = OracleConnect.GetOracleConnect()){
            String row[] = new String [8];
            String sql = "Select * from CUSTOMER";
            Statement stat = con.createStatement();
            ResultSet rs = stat.executeQuery(sql);
            while (rs.next()){
                row[0] = rs.getString(1);
                row[1] = rs.getString(2);
                row[2] = rs.getString(3);
                row[3] = rs.getString(4);
                row[4] = rs.getString(5);
                row[5] = rs.getString(6);
                row[6] = rs.getString(7);
                row[7] = rs.getString(8);

                tblModelTT.addRow(row);
            }
                    
        }
        catch(Exception e)
        {
            System.out.print(e);
        }
     tbKhachHang.setModel(tblModelTT);
     setVisible(true);
}                        
    private void tbKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKhachHangMouseClicked
        // TODO add your handling code here:
        int indexTB = tbKhachHang.getSelectedRow();
        if (indexTB < tblModelTT.getRowCount() && indexTB >=0)
        txtMaKH.setText(tblModelTT.getValueAt(indexTB, 0).toString());
        txtusername.setText(tblModelTT.getValueAt(indexTB, 1).toString());
        txtTenKH.setText(tblModelTT.getValueAt(indexTB, 2).toString());
        txtSdt.setText(tblModelTT.getValueAt(indexTB, 3).toString());
        txtDiaChi.setText(tblModelTT.getValueAt(indexTB, 4).toString());
        txtSLDat.setText(tblModelTT.getValueAt(indexTB, 5).toString());
        txtLoaiKH.setText(tblModelTT.getValueAt(indexTB, 6).toString());
        txtGhiChu.setText(tblModelTT.getValueAt(indexTB, 7).toString());
    }//GEN-LAST:event_tbKhachHangMouseClicked

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        // TODO add your handling code here:
        int indexTB = tbKhachHang.getSelectedRow();
        int ret = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa", "Xóa thông"
            + "tin khách hàng", JOptionPane.YES_NO_OPTION);
        if (ret == JOptionPane.YES_OPTION) {
            KhachHang kh = new KhachHang();
            int countRecord = kh.XoaKhachHang(txtMaKH.getText());
            if (countRecord > 0) {
                JOptionPane.showMessageDialog(this, "Xóa thông tin khách hàng thành công");
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thông tin khách hàng thất bại");
            }
            if (indexTB < tblModelTT.getRowCount() && indexTB >= 0) {
                tblModelTT.removeRow(indexTB);
            }
        }
    }//GEN-LAST:event_btXoaActionPerformed

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed
        // TODO add your handling code here:
        int ret = JOptionPane.showConfirmDialog(null,"Bạn có muốn sửa dữ liệu",
            "Sửa dữ liệu",JOptionPane.YES_NO_OPTION);
        if (ret == JOptionPane.YES_OPTION) {
            String maKH = txtMaKH.getText();
            String tendn = txtusername.getText();
            String tenKH = txtTenKH.getText();
            String sdt = txtSdt.getText();
            String diachi = txtDiaChi.getText();
            String sldat = txtSLDat.getText();
            String loaiKH = txtLoaiKH.getText();           
            String ghichu = txtGhiChu.getText();
            int indexTB = tbKhachHang.getSelectedRow();

            if (maKH.equals(tblModelTT.getValueAt(indexTB, 0))) {
                if (tendn.equals(tblModelTT.getValueAt(indexTB, 1))) {
                    KhachHang kh = new KhachHang();
                //Lấy kết quả từ CSDL
                int countRecord = kh.SuaTTKhachHang(maKH,tenKH, sdt, diachi, sldat, loaiKH, ghichu);
                if(countRecord>0){
                    JOptionPane.showMessageDialog(this, "Sửa thông tin khách hàng thành công!");
                }
                else{
                    JOptionPane.showMessageDialog(this, "Sửa thông tin khách hàng thất bại!");
                }
                if (indexTB < tblModelTT.getRowCount() && indexTB >= 0) {
                    tblModelTT.setValueAt(txtusername.getText(), indexTB, 1);
                    tblModelTT.setValueAt(txtTenKH.getText(), indexTB, 2);
                    tblModelTT.setValueAt(txtSdt.getText(), indexTB, 3);
                    tblModelTT.setValueAt(txtDiaChi.getText(), indexTB, 4);
                }
                }else{
                    JOptionPane.showMessageDialog(this, "Không được sửa tên đăng nhập của khách hàng");
                }
                
            } else {
                JOptionPane.showMessageDialog(this, "Không được sửa mã khách hàng");
            }
        }
    }//GEN-LAST:event_btSuaActionPerformed

    private void btThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThoatActionPerformed
        // TODO add your handling code here:
        int ret = JOptionPane.showConfirmDialog(null,"Bạn có muốn thoát",
            "Thoát",JOptionPane.YES_NO_OPTION);
        if(ret == JOptionPane.YES_OPTION)
        System.exit(0);
    }//GEN-LAST:event_btThoatActionPerformed

    private void btTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimKiemActionPerformed
        String gtri = this.txtTimKiem.getText();
        if (gtri.length() > 0) {
            String sql = "select * from BEVERAGE where BEVERAGEID like '%" + gtri + "%' ";
            try ( Connection con = OracleConnect.GetOracleConnect()) {
                // Tạo đối tượng thực thi câu lệnh Select
                PreparedStatement ps = con.prepareStatement(sql);
                ResultSet rs = ps.executeQuery(sql);
                if (rs.next()) {
                    tblModelTT.getDataVector().removeAllElements();
                    while (rs.next()) {
                        String row[] = new String[5];
                        row[0] = rs.getString(1);
                        row[1] = rs.getString(2);
                        row[2] = rs.getString(3);
                        row[3] = rs.getString(4);
                        row[4] = rs.getString(5);
                        tblModelTT.addRow(row);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Không tìm thấy đồ uống");
                }
            } catch (Exception e) {
                System.out.print(e);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Hãy nhập mã đồ uống để tìm kiếm");
        }
    }//GEN-LAST:event_btTimKiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyKhachHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSua;
    private javax.swing.JButton btThoat;
    private javax.swing.JButton btTimKiem;
    private javax.swing.JButton btXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbKhachHang;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtLoaiKH;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtSLDat;
    private javax.swing.JTextField txtSdt;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
