/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import ConnectDB.ConnectionUtils;
import Process.DungCu;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kim Lien
 */
public class QuanLyDungCu extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyDungCu
     */
    public QuanLyDungCu() {
        initComponents();
        setVisible(true);
        TaoTableDungCu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btXoa = new javax.swing.JButton();
        btSua = new javax.swing.JButton();
        txtSLConLai = new javax.swing.JTextField();
        btThoat = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btTimKiem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtMucGia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtGhiChu = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMaDungCu = new javax.swing.JTextField();
        txtTimKiem = new javax.swing.JTextField();
        txtTenDungCu = new javax.swing.JTextField();
        jPanelTitle = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbDungCu = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelLogOut = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý dụng cụ");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btXoa.setBackground(new java.awt.Color(238, 152, 154));
        btXoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icon_delete.png"))); // NOI18N
        btXoa.setText("Xóa");
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });
        jPanel1.add(btXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 558, -1, 30));

        btSua.setBackground(new java.awt.Color(153, 204, 255));
        btSua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icon_update.png"))); // NOI18N
        btSua.setText("Sửa");
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });
        jPanel1.add(btSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 558, -1, -1));
        jPanel1.add(txtSLConLai, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 240, 80, -1));

        btThoat.setBackground(new java.awt.Color(224, 187, 228));
        btThoat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icon_exit.png"))); // NOI18N
        btThoat.setText("Thoát");
        btThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThoatActionPerformed(evt);
            }
        });
        jPanel1.add(btThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 558, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Nhập mã dụng cụ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 102, -1, -1));

        btTimKiem.setBackground(new java.awt.Color(153, 204, 255));
        btTimKiem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icon_search.png"))); // NOI18N
        btTimKiem.setText("Tìm kiếm");
        btTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimKiemActionPerformed(evt);
            }
        });
        jPanel1.add(btTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 94, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ID-San.png"))); // NOI18N
        jLabel1.setText("Mã dụng cụ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 239, -1, -1));
        jPanel1.add(txtMucGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 288, 113, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/TenDungCu.png"))); // NOI18N
        jLabel2.setText("Tên dụng cụ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 286, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/SoLuongConlai.png"))); // NOI18N
        jLabel3.setText("Số lượng còn lại");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 239, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(174, 160, 219));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Thông tin chi tiết dụng cụ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 176, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/MucGia.png"))); // NOI18N
        jLabel4.setText("Mức giá");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 287, -1, -1));
        jPanel1.add(txtGhiChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 339, 93, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ghiChu.png"))); // NOI18N
        jLabel6.setText("Ghi chú");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 338, -1, -1));

        txtMaDungCu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaDungCuActionPerformed(evt);
            }
        });
        jPanel1.add(txtMaDungCu, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 240, 91, -1));

        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });
        jPanel1.add(txtTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 98, 152, -1));

        txtTenDungCu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenDungCuActionPerformed(evt);
            }
        });
        jPanel1.add(txtTenDungCu, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 287, 93, -1));

        jPanelTitle.setBackground(new java.awt.Color(170, 227, 167));

        jLabel46.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/QuanLiDungCu.png"))); // NOI18N
        jLabel46.setText("QUẢN LÝ DỤNG CỤ");

        javax.swing.GroupLayout jPanelTitleLayout = new javax.swing.GroupLayout(jPanelTitle);
        jPanelTitle.setLayout(jPanelTitleLayout);
        jPanelTitleLayout.setHorizontalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitleLayout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jLabel46)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTitleLayout.setVerticalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel46)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 623, -1));

        tbDungCu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 1, true));
        tbDungCu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã dụng cụ", "Tên dụng cụ", "Số lượng còn lại", "Mức giá", "Ghi chú"
            }
        ));
        tbDungCu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDungCuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbDungCu);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 392, 500, 154));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 157, 611, 10));

        jLabelLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/logout.png"))); // NOI18N
        jLabelLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLogOutMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 619, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
DefaultTableModel tblModelTT;
public void TaoTableDungCu(){
        tblModelTT = new DefaultTableModel();
        String tieuDe[]={"Mã dụng cụ","Tên dụng cụ","Số lượng còn lại","Mức giá",
            "Ghi chú"};
        tblModelTT.setColumnIdentifiers(tieuDe);

        try(Connection con = ConnectionUtils.getMyConnection()){
            String row[] = new String [5];
            String sql = "Select * from EQUIPMENT";
            Statement stat = con.createStatement();
            ResultSet rs = stat.executeQuery(sql);
            while (rs.next()){
                row[0] = rs.getString(1);
                row[1] = rs.getString(2);
                row[2] = rs.getString(3);
                row[3] = rs.getString(4);
                row[4] = rs.getString(5);
                tblModelTT.addRow(row);
            }
        }
        catch(Exception e)
        {
            System.out.print(e);
        }
     tbDungCu.setModel(tblModelTT);
     setVisible(true);
}                                  

    private void txtTenDungCuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenDungCuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenDungCuActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        // TODO add your handling code here:
        int indexTB = tbDungCu.getSelectedRow();
        int ret = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa", "Xóa thông"
            + "tin dụng cụ", JOptionPane.YES_NO_OPTION);
        if (ret == JOptionPane.YES_OPTION) {
            DungCu dc = new DungCu();
            int countRecord = dc.XoaDungCu(txtMaDungCu.getText());
            if (countRecord > 0) {
                JOptionPane.showMessageDialog(this, "Xóa thông tin dụng cụ thành công");
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thông tin dụng cụ thất bại");
            }
            if (indexTB < tblModelTT.getRowCount() && indexTB >= 0) {
                tblModelTT.removeRow(indexTB);
            }
        }
    }//GEN-LAST:event_btXoaActionPerformed

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here

    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed
        // TODO add your handling code here:
        int ret = JOptionPane.showConfirmDialog(null,"Bạn có muốn sửa dữ liệu",
            "Sửa dữ liệu",JOptionPane.YES_NO_OPTION);
        if (ret == JOptionPane.YES_OPTION) {
            String madungcu = txtMaDungCu.getText();
            String tendungcu = txtTenDungCu.getText();
            String slconlai = txtSLConLai.getText();
            String mucgia = txtMucGia.getText();
            String ghichu = txtGhiChu.getText();
            int indexTB = tbDungCu.getSelectedRow();

            if (madungcu.equals(tblModelTT.getValueAt(indexTB, 0))) {
                DungCu dc = new DungCu();
                //Lấy kết quả từ CSDL
                int countRecord = dc.SuaDungCu(madungcu, tendungcu, slconlai, mucgia, ghichu);
                if(countRecord>0){
                    JOptionPane.showMessageDialog(this, "Sửa thông tin dụng cụ thành công!");
                }
                else{
                    JOptionPane.showMessageDialog(this, "Sửa thông tin dụng cụ thất bại!");
                }
                if (indexTB < tblModelTT.getRowCount() && indexTB >= 0) {
                    tblModelTT.setValueAt(txtTenDungCu.getText(), indexTB, 1);
                    tblModelTT.setValueAt(txtSLConLai.getText(), indexTB, 2);
                    tblModelTT.setValueAt(txtMucGia.getText(), indexTB, 3);
                    tblModelTT.setValueAt(txtGhiChu.getText(), indexTB, 4);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Không được sửa mã dụng cụ");
            }
        }
    }//GEN-LAST:event_btSuaActionPerformed

    private void btThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThoatActionPerformed
        // TODO add your handling code here:
        int ret = JOptionPane.showConfirmDialog(null,"Bạn có muốn thoát",
            "Thoát",JOptionPane.YES_NO_OPTION);
        if(ret == JOptionPane.YES_OPTION)
        System.exit(0);
    }//GEN-LAST:event_btThoatActionPerformed

    private void btTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimKiemActionPerformed
        String gtri = this.txtTimKiem.getText();
        if (gtri.length() > 0) {
            String sql = "select * from EQUIPMENT where EQUIPMENTID like '%" + gtri + "%' ";
            try ( Connection con = ConnectionUtils.getMyConnection()) {
                // Tạo đối tượng thực thi câu lệnh Select
                PreparedStatement ps = con.prepareStatement(sql);
                ResultSet rs = ps.executeQuery(sql);
                if (rs.next()) {
                    tblModelTT.getDataVector().removeAllElements();
                    while (rs.next()) {
                        String row[] = new String[5];
                        row[0] = rs.getString(1);
                        row[1] = rs.getString(2);
                        row[2] = rs.getString(3);
                        row[3] = rs.getString(4);
                        row[4] = rs.getString(5);
                        tblModelTT.addRow(row);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Không tìm thấy dụng cụ");
                }
            } catch (Exception e) {
                System.out.print(e);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Hãy nhập mã dụng cụ để tìm kiếm");
        }
    }//GEN-LAST:event_btTimKiemActionPerformed

    private void tbDungCuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDungCuMouseClicked
        // TODO add your handling code here:
        int indexTB = tbDungCu.getSelectedRow();
        if (indexTB < tblModelTT.getRowCount() && indexTB >=0)
        txtMaDungCu.setText(tblModelTT.getValueAt(indexTB, 0).toString());
        txtTenDungCu.setText(tblModelTT.getValueAt(indexTB, 1).toString());
        txtSLConLai.setText(tblModelTT.getValueAt(indexTB, 2).toString());
        txtMucGia.setText(tblModelTT.getValueAt(indexTB, 3).toString());
        txtGhiChu.setText(tblModelTT.getValueAt(indexTB, 4).toString());
    }//GEN-LAST:event_tbDungCuMouseClicked

    private void txtMaDungCuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaDungCuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaDungCuActionPerformed

    private void jLabelLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogOutMouseClicked
        // TODO add your handling code here:
        this.toBack();
        setVisible(false);
        new ManHinhChinh_NhanVien().toFront();
        new ManHinhChinh_NhanVien().setState(java.awt.Frame.NORMAL);
    }//GEN-LAST:event_jLabelLogOutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyDungCu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyDungCu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyDungCu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyDungCu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyDungCu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSua;
    private javax.swing.JButton btThoat;
    private javax.swing.JButton btTimKiem;
    private javax.swing.JButton btXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelLogOut;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelTitle;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tbDungCu;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtMaDungCu;
    private javax.swing.JTextField txtMucGia;
    private javax.swing.JTextField txtSLConLai;
    private javax.swing.JTextField txtTenDungCu;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
