/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import ConnectDB.OracleConnect;
import Process.DoUong;
import Process.SanTheThao;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;
import sportfieldmanagement.ConnectDB;

/**
 *
 * @author Kim Lien
 */
public class QuanLyDoUong extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyDoUong
     */
    public QuanLyDoUong() {
        initComponents();
        setVisible(true);
        TaoTableDoUong();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMucGia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtGhiChu = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbDoUong = new javax.swing.JTable();
        btXoa = new javax.swing.JButton();
        btSua = new javax.swing.JButton();
        btThoat = new javax.swing.JButton();
        btTimKiem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMaDoUong = new javax.swing.JTextField();
        txtTenDoUong = new javax.swing.JTextField();
        txtTimKiem = new javax.swing.JTextField();
        txtSLConLai = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtMucGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 238, 254, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Thông tin chi tiết đồ uống");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 481, 27));
        getContentPane().add(txtGhiChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 279, 254, -1));

        tbDoUong.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 1, true));
        tbDoUong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã đồ uống", "Tên đồ uống", "Số lượng còn lại", "Mức giá", "Ghi chú"
            }
        ));
        tbDoUong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDoUongMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbDoUong);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 317, 660, 140));

        btXoa.setBackground(new java.awt.Color(153, 204, 255));
        btXoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icon_delete.png"))); // NOI18N
        btXoa.setText("Xóa");
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, -1, 38));

        btSua.setBackground(new java.awt.Color(153, 204, 255));
        btSua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icon_update.png"))); // NOI18N
        btSua.setText("Sửa");
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });
        getContentPane().add(btSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, -1, 35));

        btThoat.setBackground(new java.awt.Color(153, 204, 255));
        btThoat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icon_exit.png"))); // NOI18N
        btThoat.setText("Thoát");
        btThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThoatActionPerformed(evt);
            }
        });
        getContentPane().add(btThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, -1, 38));

        btTimKiem.setBackground(new java.awt.Color(153, 204, 255));
        btTimKiem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icon_search.png"))); // NOI18N
        btTimKiem.setText("Tìm kiếm");
        btTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimKiemActionPerformed(evt);
            }
        });
        getContentPane().add(btTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Mã đồ uống");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 119, 74, 24));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Tên đồ uống");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 161, 74, 19));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Số lượng còn lại");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 199, -1, 17));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Mức giá");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 237, 94, 19));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Ghi chú");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 275, 74, 24));
        getContentPane().add(txtMaDoUong, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 254, -1));

        txtTenDoUong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenDoUongActionPerformed(evt);
            }
        });
        getContentPane().add(txtTenDoUong, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 162, 254, -1));

        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });
        getContentPane().add(txtTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 254, 30));
        getContentPane().add(txtSLConLai, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 199, 254, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Nhập mã đồ uống");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 55));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icon_beverage.jpeg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 20, 700, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents
DefaultTableModel tblModelTT;
public void TaoTableDoUong(){
        tblModelTT = new DefaultTableModel();
        String tieuDe[]={"Mã đồ uống","Tên đồ uống","Số lượng còn lại","Mức giá",
            "Ghi chú"};
        tblModelTT.setColumnIdentifiers(tieuDe);

        try(Connection con = OracleConnect.GetOracleConnect()){
            String row[] = new String [5];
            String sql = "Select * from BEVERAGE";
            Statement stat = con.createStatement();
            ResultSet rs = stat.executeQuery(sql);
            while (rs.next()){
                row[0] = rs.getString(1);
                row[1] = rs.getString(2);
                row[2] = rs.getString(3);
                row[3] = rs.getString(4);
                row[4] = rs.getString(5);
                tblModelTT.addRow(row);
            }
                    
        }
        catch(Exception e)
        {
            System.out.print(e);
        }
     tbDoUong.setModel(tblModelTT);
     setVisible(true);
}
   
    private void tbDoUongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDoUongMouseClicked
        // TODO add your handling code here:
        int indexTB = tbDoUong.getSelectedRow();
        if (indexTB < tblModelTT.getRowCount() && indexTB >=0)
        txtMaDoUong.setText(tblModelTT.getValueAt(indexTB, 0).toString());
        txtTenDoUong.setText(tblModelTT.getValueAt(indexTB, 1).toString());
        txtSLConLai.setText(tblModelTT.getValueAt(indexTB, 2).toString());
        txtMucGia.setText(tblModelTT.getValueAt(indexTB, 3).toString());
        txtGhiChu.setText(tblModelTT.getValueAt(indexTB, 4).toString());
    }//GEN-LAST:event_tbDoUongMouseClicked

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        // TODO add your handling code here:
        int indexTB = tbDoUong.getSelectedRow();
        int ret = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa", "Xóa thông"
            + "tin đồ uống", JOptionPane.YES_NO_OPTION);
        if (ret == JOptionPane.YES_OPTION) {
            DoUong douong = new DoUong();
            int countRecord = douong.XoaDoUong(txtMaDoUong.getText());
            if (countRecord > 0) {
                JOptionPane.showMessageDialog(this, "Xóa thông tin đồ uống thành công");
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thông tin đồ uống thất bại");
            }
            if (indexTB < tblModelTT.getRowCount() && indexTB >= 0) {
                tblModelTT.removeRow(indexTB);
            }
        }
    }//GEN-LAST:event_btXoaActionPerformed

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed
        // TODO add your handling code here:
        int ret = JOptionPane.showConfirmDialog(null,"Bạn có muốn sửa dữ liệu",
            "Sửa dữ liệu",JOptionPane.YES_NO_OPTION);
        if (ret == JOptionPane.YES_OPTION) {
            String madouong = txtMaDoUong.getText();
            String tendouong = txtTenDoUong.getText();
            String slconlai = txtSLConLai.getText();
            String mucgia = txtMucGia.getText();
            String ghichu = txtGhiChu.getText();
            int indexTB = tbDoUong.getSelectedRow();

            if (madouong.equals(tblModelTT.getValueAt(indexTB, 0))) {
                 DoUong douong = new DoUong();
                //Lấy kết quả từ CSDL
                int countRecord = douong.SuaDoUong(madouong, tendouong, slconlai, mucgia, ghichu);
                if(countRecord>0){
                    JOptionPane.showMessageDialog(this, "Sửa thông tin đồ uống thành công!");
                }
                else{
                    JOptionPane.showMessageDialog(this, "Sửa thông tin đồ uống thất bại!");
                }
                if (indexTB < tblModelTT.getRowCount() && indexTB >= 0) {
                    tblModelTT.setValueAt(txtTenDoUong.getText(), indexTB, 1);
                    tblModelTT.setValueAt(txtSLConLai.getText(), indexTB, 2);
                    tblModelTT.setValueAt(txtMucGia.getText(), indexTB, 3);
                    tblModelTT.setValueAt(txtGhiChu.getText(), indexTB, 4);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Không được sửa mã đồ uống");
            }
        }
    }//GEN-LAST:event_btSuaActionPerformed

    private void btThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThoatActionPerformed
        // TODO add your handling code here:
        int ret = JOptionPane.showConfirmDialog(null,"Bạn có muốn thoát",
            "Thoát",JOptionPane.YES_NO_OPTION);
        if(ret == JOptionPane.YES_OPTION)
        System.exit(0);
    }//GEN-LAST:event_btThoatActionPerformed

    private void btTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimKiemActionPerformed
        String gtri = this.txtTimKiem.getText();
        if (gtri.length() > 0) {
            String sql = "select * from BEVERAGE where BEVERAGEID like '%" + gtri + "%' ";
            try ( Connection con = OracleConnect.GetOracleConnect()) {
                // Tạo đối tượng thực thi câu lệnh Select
                PreparedStatement ps = con.prepareStatement(sql);
                ResultSet rs = ps.executeQuery(sql);
                if (rs.next()) {
                    tblModelTT.getDataVector().removeAllElements();
                    while (rs.next()) {
                        String row[] = new String[5];
                        row[0] = rs.getString(1);
                        row[1] = rs.getString(2);
                        row[2] = rs.getString(3);
                        row[3] = rs.getString(4);
                        row[4] = rs.getString(5);
                        tblModelTT.addRow(row);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Không tìm thấy đồ uống");
                }
            } catch (Exception e) {
                System.out.print(e);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Hãy nhập mã đồ uống để tìm kiếm");
        }
    }//GEN-LAST:event_btTimKiemActionPerformed

    private void txtTenDoUongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenDoUongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenDoUongActionPerformed

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here

           
      
    }//GEN-LAST:event_txtTimKiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyDoUong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyDoUong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyDoUong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyDoUong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyDoUong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSua;
    private javax.swing.JButton btThoat;
    private javax.swing.JButton btTimKiem;
    private javax.swing.JButton btXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbDoUong;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtMaDoUong;
    private javax.swing.JTextField txtMucGia;
    private javax.swing.JTextField txtSLConLai;
    private javax.swing.JTextField txtTenDoUong;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
