/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import ConnectDB.ConnectionUtils;
import java.awt.Color;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.CallableStatement;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Duc Tai
 */
public class ThanhToan extends javax.swing.JFrame {
    ImageIcon muiTenXuong;
    ImageIcon muiTenPhai;
    DefaultTableModel tableHD;
    /**
     * Creates new form ThanhToan
     */
    public ThanhToan() {
        initComponents();
        this.setLocationRelativeTo(null);
        muiTenXuong= new ImageIcon("src/Resources/muiten_xuong.png");
        muiTenPhai = new ImageIcon("src/Resources/muiten_phai.png");
        jpChua.setVisible(false);
        tableHD = (DefaultTableModel) jTableHD.getModel();
        jbtThanhToan.setVisible(false);
        
    }
String userName="";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbChuaThanhToan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlChua = new javax.swing.JLabel();
        jbDaThanhToan = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jlDa = new javax.swing.JLabel();
        jpChua = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableHD = new javax.swing.JTable();
        jbtXemChiTiet = new javax.swing.JButton();
        jbtThanhToan = new javax.swing.JButton();
        jPanelTitle = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jlDSChua = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbChuaThanhToan.setBackground(new java.awt.Color(255, 156, 159));
        jbChuaThanhToan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbChuaThanhToanMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/unpaid.png"))); // NOI18N
        jLabel1.setText("Chưa thanh toán");

        jlChua.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlChua.setForeground(new java.awt.Color(255, 255, 255));
        jlChua.setText("jLabel3");

        javax.swing.GroupLayout jbChuaThanhToanLayout = new javax.swing.GroupLayout(jbChuaThanhToan);
        jbChuaThanhToan.setLayout(jbChuaThanhToanLayout);
        jbChuaThanhToanLayout.setHorizontalGroup(
            jbChuaThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbChuaThanhToanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1))
            .addGroup(jbChuaThanhToanLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jlChua))
        );
        jbChuaThanhToanLayout.setVerticalGroup(
            jbChuaThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbChuaThanhToanLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlChua)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jbChuaThanhToan, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 136, -1, -1));

        jbDaThanhToan.setBackground(new java.awt.Color(155, 209, 167));
        jbDaThanhToan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbDaThanhToanMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/paid.png"))); // NOI18N
        jLabel2.setText("Đã thanh toán");

        jlDa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlDa.setForeground(new java.awt.Color(255, 255, 255));
        jlDa.setText("jLabel4");

        javax.swing.GroupLayout jbDaThanhToanLayout = new javax.swing.GroupLayout(jbDaThanhToan);
        jbDaThanhToan.setLayout(jbDaThanhToanLayout);
        jbDaThanhToanLayout.setHorizontalGroup(
            jbDaThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbDaThanhToanLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jbDaThanhToanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlDa)
                .addGap(59, 59, 59))
        );
        jbDaThanhToanLayout.setVerticalGroup(
            jbDaThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbDaThanhToanLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlDa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jbDaThanhToan, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 136, -1, 99));

        jpChua.setBackground(new java.awt.Color(255, 255, 255));

        jTableHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Số lượng sân", "Ngày hóa đơn", "Tổng tiền"
            }
        ));
        jTableHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableHDMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableHD);

        jbtXemChiTiet.setBackground(new java.awt.Color(161, 201, 241));
        jbtXemChiTiet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/kinh.png"))); // NOI18N
        jbtXemChiTiet.setText("Xem chi tiết");
        jbtXemChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtXemChiTietActionPerformed(evt);
            }
        });

        jbtThanhToan.setBackground(new java.awt.Color(0, 255, 0));
        jbtThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/pay.png"))); // NOI18N
        jbtThanhToan.setText("Thanh toán");
        jbtThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtThanhToanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpChuaLayout = new javax.swing.GroupLayout(jpChua);
        jpChua.setLayout(jpChuaLayout);
        jpChuaLayout.setHorizontalGroup(
            jpChuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpChuaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(jpChuaLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpChuaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtThanhToan)
                .addGap(37, 37, 37)
                .addComponent(jbtXemChiTiet)
                .addGap(14, 14, 14))
        );
        jpChuaLayout.setVerticalGroup(
            jpChuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpChuaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jpChuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtXemChiTiet)
                    .addComponent(jbtThanhToan))
                .addContainerGap())
        );

        jPanel1.add(jpChua, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jPanelTitle.setBackground(new java.awt.Color(158, 169, 205));

        jLabel46.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/debit-card.png"))); // NOI18N
        jLabel46.setText("THANH TOÁN");

        javax.swing.GroupLayout jPanelTitleLayout = new javax.swing.GroupLayout(jPanelTitle);
        jPanelTitle.setLayout(jPanelTitleLayout);
        jPanelTitleLayout.setHorizontalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTitleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel46)
                .addGap(232, 232, 232))
        );
        jPanelTitleLayout.setVerticalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel46)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, -1));

        jlDSChua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/muiten_phai.png"))); // NOI18N
        jlDSChua.setText("Danh sách hóa đơn");
        jlDSChua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlDSChuaMouseClicked(evt);
            }
        });
        jPanel1.add(jlDSChua, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 273, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void setThongTin(String cusUserName){
        userName =cusUserName;
        String customerID = returnCusID(userName);
        try(Connection conn = ConnectionUtils.getMyConnection()){
            String sql1 ="SELECT COUNT(*) "
                    + "FROM SCHEDULE WHERE customerid='"+customerID+"' "
                    + "AND paymentstatus = 'Chưa thanh toán'";
            PreparedStatement ps1= conn.prepareStatement(sql1);
            ResultSet rs1 = ps1.executeQuery();
            int chuaThanhToan = 0;
            if(rs1.next()){
                chuaThanhToan = rs1.getInt("COUNT(*)");
            }
            jlChua.setText("("+chuaThanhToan+")");
            rs1.close();
            ps1.close();
            
     
            String sql2 ="SELECT COUNT(*) "
                    + "FROM SCHEDULE WHERE customerid='"+customerID+"' "
                    + "AND paymentstatus = 'Đã thanh toán'";
            PreparedStatement ps2= conn.prepareStatement(sql2);
            ResultSet rs2 = ps2.executeQuery();
            int daThanhToan = 0;
            if(rs2.next()){
                daThanhToan = rs2.getInt("COUNT(*)");
            }
            jlDa.setText("("+daThanhToan+")");
            
            rs2.close();
            ps2.close();
            conn.close();
        }catch(Exception e){
            System.out.println(e);
            e.printStackTrace();
        }
        

    }
    String returnCusID(String userName1){
        String customerID = "";
        try(Connection conn = ConnectionUtils.getMyConnection()){
            String sql= "SELECT CUSTOMERID FROM CUSTOMER WHERE cus_username ='"+userName1+"'";
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            if(rs.next()){
                customerID = rs.getString("CUSTOMERID");
            }
            rs.close();
            ps.close();
            conn.close();
            return customerID;
            
        }catch(Exception e){
            System.out.println(e);
            e.printStackTrace();
        }
        
        return customerID;
    }
    
    int dsHoaDon =1;
    private void jlDSChuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlDSChuaMouseClicked
        // TODO add your handling code here:
        if(dsHoaDon == 1){
            jlDSChua.setIcon(muiTenXuong);
            jpChua.setVisible(true);
            dsHoaDon =0;
            
        }else if(dsHoaDon == 0){
            jlDSChua.setIcon(muiTenPhai);
            jpChua.setVisible(false);
            dsHoaDon =1;
        }
    }//GEN-LAST:event_jlDSChuaMouseClicked

    private void jbChuaThanhToanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbChuaThanhToanMouseClicked
        // TODO add your handling code here:
        tableHD.setRowCount(0);
        jbtThanhToan.setVisible(true);
        jbtThanhToan.setEnabled(false);
        try(Connection conn = ConnectionUtils.getMyConnection()){
            String sql = "SELECT BILL.BILLID, COUNT(*) FIELDNAME, BILLDATE, TOTAL " +
                        "FROM BILL, FIELD, SCHEDULEDETAILS, USER_ACCOUNT, CUSTOMER, SCHEDULE " +
                        "WHERE bill.billid = scheduledetails.billid AND  field.fieldid = scheduledetails.fieldid " +
                        "        AND bill.customerid = customer.customerid  AND user_account.username = customer.cus_username " +
                        "        AND schedule.bookid = scheduledetails.bookid AND username ='"+userName+"'" +
                        "        AND PAYMENTSTATUS = 'Chưa thanh toán' "+
                        "GROUP BY bill.billid, billdate , total";
            PreparedStatement ps = conn.prepareStatement(sql);
            //ps.setString(1,"%"+ userName+"%");
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                java.sql.Date billDate= rs.getDate("BILLDATE");
                System.out.println(rs.getString("BILLID"));
                tableHD.addRow(new Object[]{
                    rs.getString("BILLID"),
                    rs.getInt("FIELDNAME"),
                    billDate.toString(),
                    rs.getDouble("TOTAL"),
                });
                tableHD.fireTableDataChanged();
            }
            rs.close();
            ps.close();
            conn.close();
        }catch(Exception e){
            System.out.println(e);
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jbChuaThanhToanMouseClicked

    private void jbDaThanhToanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbDaThanhToanMouseClicked
        // TODO add your handling code here:
        tableHD.setRowCount(0);
        jbtThanhToan.setVisible(false);
        try(Connection conn = ConnectionUtils.getMyConnection()){
            String sql = "SELECT BILL.BILLID, COUNT(*) FIELDNAME, BILLDATE, TOTAL " +
                        "FROM BILL, FIELD, SCHEDULEDETAILS, USER_ACCOUNT, CUSTOMER, SCHEDULE " +
                        "WHERE bill.billid = scheduledetails.billid AND  field.fieldid = scheduledetails.fieldid " +
                        "        AND bill.customerid = customer.customerid  AND user_account.username = customer.cus_username " +
                        "        AND schedule.bookid = scheduledetails.bookid AND username ='"+userName+"'" +
                        "        AND PAYMENTSTATUS = 'Đã thanh toán' "+
                        "GROUP BY bill.billid, billdate , total";
            PreparedStatement ps = conn.prepareStatement(sql);
            //ps.setString(1,"%"+ userName+"%");
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                java.sql.Date billDate= rs.getDate("BILLDATE");
                System.out.println(rs.getString("BILLID"));
                tableHD.addRow(new Object[]{
                    rs.getString("BILLID"),
                    rs.getString("FIELDNAME"),
                    billDate.toString(),
                    rs.getDouble("TOTAL"),
                });
                tableHD.fireTableDataChanged();
            }
            rs.close();
            ps.close();
            conn.close();
        }catch(Exception e){
            System.out.println(e);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jbDaThanhToanMouseClicked

    private void jbtXemChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtXemChiTietActionPerformed
        // TODO add your handling code here:
        String billID = (String) tableHD.getValueAt(jTableHD.getSelectedRow(), 0);
        HoaDon hd = new HoaDon();
        String customerID = returnCusID(userName);
        hd.setThongTinKhachHang(customerID);
        hd.thanhToan(billID);
        
        //this.toBack();
        hd.setVisible(true);
        hd.toFront();
        hd.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_jbtXemChiTietActionPerformed

    private void jbtThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtThanhToanActionPerformed
        // TODO add your handling code here:
        
       XacNhanThanhToan xn = new XacNhanThanhToan();
       xn.userName = userName;
       xn.billID = (String) tableHD.getValueAt(jTableHD.getSelectedRow(), 0);
       //this.toBack();
       xn.setVisible(true);
       xn.toFront();
       xn.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jbtThanhToanActionPerformed

    private void jTableHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableHDMouseClicked
        // TODO add your handling code here:
        if(jTableHD.getSelectedRow()>=0){
            jbtThanhToan.setEnabled(true);
        }
    }//GEN-LAST:event_jTableHDMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThanhToan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelTitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableHD;
    private javax.swing.JPanel jbChuaThanhToan;
    private javax.swing.JPanel jbDaThanhToan;
    private javax.swing.JButton jbtThanhToan;
    private javax.swing.JButton jbtXemChiTiet;
    private javax.swing.JLabel jlChua;
    private javax.swing.JLabel jlDSChua;
    private javax.swing.JLabel jlDa;
    private javax.swing.JPanel jpChua;
    // End of variables declaration//GEN-END:variables
}
