/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Process.NhanVien;
import Process.User;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author minhh
 */
public class DangKy_NhanVien extends javax.swing.JFrame {

    /**
     * Creates new form DangKy_NhanVien
     */
    ArrayList<String> listMaQL = null;
    public DangKy_NhanVien() {
        initComponents();
        setListQuanLy();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TenDN = new javax.swing.JTextField();
        MK = new javax.swing.JPasswordField();
        ConfirmMK = new javax.swing.JPasswordField();
        SoDT = new javax.swing.JTextField();
        DiaChi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Note = new javax.swing.JTextPane();
        jLabel10 = new javax.swing.JLabel();
        TenNhanVien = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TenQuanLy = new javax.swing.JComboBox<>();
        DangKy = new javax.swing.JButton();
        Huy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Tên đăng nhập");

        jLabel4.setText("Mật khẩu");

        jLabel5.setText("Nhập lại mật khẩu");

        jLabel6.setText("Số điện thoại");

        jLabel7.setText("Địa chỉ");

        jLabel9.setText("Ghi chú");

        DiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaChiActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(Note);

        jLabel10.setText("Tên nhân viên");

        jLabel1.setText("Quản lý");

        DangKy.setText("Đăng ký");
        DangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DangKyActionPerformed(evt);
            }
        });

        Huy.setText("Hủy");
        Huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(jLabel10)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(61, 61, 61)))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TenDN)
                    .addComponent(TenNhanVien)
                    .addComponent(MK)
                    .addComponent(ConfirmMK)
                    .addComponent(SoDT)
                    .addComponent(DiaChi)
                    .addComponent(jScrollPane1)
                    .addComponent(TenQuanLy, 0, 256, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(DangKy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(Huy)
                .addGap(98, 98, 98))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(TenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TenDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(MK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ConfirmMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TenQuanLy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(SoDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DangKy)
                    .addComponent(Huy))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiaChiActionPerformed

    private void DangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DangKyActionPerformed
        // TODO add your handling code here:
        String ten = TenNhanVien.getText();
        String tenDN = TenDN.getText();
        String MatKhau = MK.getText();
        String XacNhanMK = ConfirmMK.getText();
        String SDT = SoDT.getText();
        String DC = DiaChi.getText();
        String GhiChu = Note.getText();
        String reg = "^(0|\\+84)(\\s|\\.)?((3[2-9])|(5[689])|(7[06-9])|(8[1-689])|(9[0-46-9]))(\\d)(\\s|\\.)?(\\d{3})(\\s|\\.)?(\\d{3})$";
        if(ten.equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên!",
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        else if(tenDN.equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên đăng nhập!",
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        else if(MatKhau.equals("")||XacNhanMK.equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mật khẩu!",
                    "ERROR", JOptionPane.ERROR_MESSAGE); 
        }
        else if(!MatKhau.equals(XacNhanMK)){
            JOptionPane.showMessageDialog(this, "Mật khẩu nhập lại không khớp!",
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        else if(SoDT.equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số điện thoại!",
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        else if(false==SDT.matches(reg)){
            JOptionPane.showMessageDialog(this, "Nhập không đúng định dạng số điện thoại!",
                    "ERROR", JOptionPane.ERROR_MESSAGE);            
        }
        else if(DC.equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập địa chỉ!",
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        else{
            NhanVien nv = new NhanVien();
            User tk= new User();
            try {
                if(tk.DK_TK_NV(tenDN,MatKhau)>0){
                    String maquanly= listMaQL.get(TenQuanLy.getSelectedIndex());
                    if(nv.DKNhanVien(tenDN,maquanly,ten,SDT,DC,GhiChu)>0){
                        JOptionPane.showMessageDialog(this,"Thêm tài khoản nhân viên thành công");
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Thêm tài khoản nhân viên thất bại",
                            "ERROR", JOptionPane.ERROR_MESSAGE);   
                    }
                }
                else{
                        JOptionPane.showMessageDialog(this, "Thêm tài khoản thất bại",
                            "ERROR", JOptionPane.ERROR_MESSAGE);                        
                }
            } catch (SQLException ex) {
                Logger.getLogger(DangKy_NhanVien.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(DangKy_NhanVien.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_DangKyActionPerformed

    private void HuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HuyActionPerformed
        // TODO add your handling code here:
        DangNhap dn = new DangNhap();
        dn.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_HuyActionPerformed

    /**
     * @param args the command line arguments
     */
    private void setListQuanLy(){
        NhanVien nv= new NhanVien();
        HashMap<String, String> listQuanLy = nv.getQuanLy();
        listMaQL = new ArrayList<String>();
        listMaQL.addAll(listQuanLy.keySet());
        ArrayList<String> listTenQL = new ArrayList<String>();
        listTenQL.addAll(listQuanLy.values());
        TenQuanLy.setModel(new DefaultComboBoxModel(listTenQL.toArray()));
        
        
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangKy_NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangKy_NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangKy_NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangKy_NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangKy_NhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ConfirmMK;
    private javax.swing.JButton DangKy;
    private javax.swing.JTextField DiaChi;
    private javax.swing.JButton Huy;
    private javax.swing.JPasswordField MK;
    private javax.swing.JTextPane Note;
    private javax.swing.JTextField SoDT;
    private javax.swing.JTextField TenDN;
    private javax.swing.JTextField TenNhanVien;
    private javax.swing.JComboBox<String> TenQuanLy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
