/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import ConnectDB.ConnectionUtils;
import java.awt.image.BufferedImage;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import net.sf.jasperreports.engine.JRAbstractChartCustomizer;
import net.sf.jasperreports.engine.JRRenderable;

/**
 *
 * @author minhh
 */
public class ThongKe extends javax.swing.JFrame {

    /**
     * Creates new form ThongKe
     */
    public ThongKe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btTKKho = new javax.swing.JButton();
        TKDTThang = new javax.swing.JButton();
        btThongKeNam = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btTKKho.setText("Thống kê kho hàng");
        btTKKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTKKhoActionPerformed(evt);
            }
        });

        TKDTThang.setText("Thống kê doanh thu theo tháng");
        TKDTThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TKDTThangActionPerformed(evt);
            }
        });

        btThongKeNam.setText("Thống kê doanh thu theo năm");
        btThongKeNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThongKeNamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btThongKeNam)
                    .addComponent(TKDTThang)
                    .addComponent(btTKKho))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addComponent(TKDTThang)
                .addGap(2, 2, 2)
                .addComponent(btThongKeNam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btTKKho)
                .addGap(98, 98, 98))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btTKKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTKKhoActionPerformed
        try {

            Connection con = ConnectionUtils.getMyConnection();
//            String e = "D:\\DoAN\\SportFieldManagement\\src\\Resourse\\ThongKeKho.jrxml";
            JasperReport report = JasperCompileManager.compileReport("src/Resourse/ThongKeKho.jrxml");
//            JasperDesign id = JRXmlLoader.load(e);
//            JasperReport jr = JasperCompileManager.compileReport(e);
            JasperPrint p = JasperFillManager.fillReport(report, new HashMap(), con);
            JasperViewer.viewReport(p, false);
            JasperExportManager.exportReportToPdfFile(p, "ThongKeKho.pdf");
        } catch (JRException | SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btTKKhoActionPerformed

    private void TKDTThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TKDTThangActionPerformed
        try {
            Connection con = ConnectionUtils.getMyConnection();
//            String e = "D:\\DoAN\\SportFieldManagement\\src\\Resourse\\ThongKeDoanhThuThang.jrxml";
            JasperReport report = JasperCompileManager.compileReport("src/Resourse/ThongKeDoanhThuThang.jrxml");
//            JasperDesign id = JRXmlLoader.load(e);
//            JasperReport jr = JasperCompileManager.compileReport(e);
            JasperPrint p = JasperFillManager.fillReport(report, new HashMap(), con);
            JasperViewer.viewReport(p, false);
//
            JasperExportManager.exportReportToPdfFile(p, "ThongKeThang.pdf");

        } catch (JRException | SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_TKDTThangActionPerformed

    private void btThongKeNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThongKeNamActionPerformed
        try {
            Connection con = ConnectionUtils.getMyConnection();
//            String e = "D:\\DoAN\\SportFieldManagement\\src\\Resourse\\ThongKeDoanhThuThang.jrxml";
            JasperReport report = JasperCompileManager.compileReport("src/Resourse/ThongKeDoanhThuTheoNam.jrxml");
//            JasperDesign id = JRXmlLoader.load(e);
//            JasperReport jr = JasperCompileManager.compileReport(e);
            JasperPrint p = JasperFillManager.fillReport(report, new HashMap(), con);
            JasperViewer.viewReport(p, false);
//
            JasperExportManager.exportReportToPdfFile(p, "ThongKeNam.pdf");

        } catch (JRException | SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        }      
    }//GEN-LAST:event_btThongKeNamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TKDTThang;
    private javax.swing.JButton btTKKho;
    private javax.swing.JButton btThongKeNam;
    // End of variables declaration//GEN-END:variables
}
